Dooter/Dooter/Models/Bookmark.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
namespace Dooter.Models
{
    public class Bookmark
    {
        public int BookmarkID { get; set; }

        [Required(ErrorMessage = "Name is required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Rating is required")]
        [Range(1.0, 5.0, ErrorMessage = "Ratings are 1 to 5 stars")]
        public double? Rating { get; set; }

        //[Required(ErrorMessage = "latitude is required")]
        public double? Latitude { get; set; }

        //[Required(ErrorMessage = "longitude is required")]
        public double? Longitude { get; set; }
    }
}

Dooter/Dooter/Controllers/FunctionalityController.cs
using Dooter.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;


namespace Dooter.Controllers
{
    public class FunctionalityController : Controller
    {
        private LocationDBContext LocationContext { get; set; }
        private BookmarkDBContext BookmarkContext { get; set; }

        public FunctionalityController(LocationDBContext locationContext, BookmarkDBContext bookmarkContext)
        {
            LocationContext = locationContext;
            BookmarkContext = bookmarkContext;
        }

        [HttpGet]
        public IActionResult AddLocation()
        {
            ViewBag.Action = "Add";
            return View("EditLocation", new Location());
        }

        [HttpGet]
        public IActionResult EditLocation(int id)
        {
            ViewBag.Action = "Edit";
            var location = LocationContext.Locations.Find(id);
            return View(location);
        }

        [HttpPost]
        public IActionResult EditLocation(Location location)
        {
            location.Latitude = 3.21;
            location.Longitude = 1.23;
            if (ModelState.IsValid)
            {
                if (location.LocationID == 0)
                    LocationContext.Locations.Add(location);
                else
                    LocationContext.Locations.Update(location);
                LocationContext.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Action = (location.LocationID == 0) ? "Add" : "Edit";
                return View(location);
            }
        }

        [HttpGet]
        public IActionResult AddBookmark()
        {
            ViewBag.Action = "Add";
            return View("EditBookmark", new Bookmark());
        }

        [HttpGet]
        public IActionResult EditBookmark(int id)
        {
            ViewBag.Action = "Edit";
            var bookmark = BookmarkContext.Bookmarks.Find(id);
            return View(bookmark);
        }

        [HttpPost]
        public IActionResult EditBookmark(Bookmark bookmark)
        {
            return View();
        }

        [HttpGet]
        public IActionResult DeleteBookmark(int id)
        {
            var location = BookmarkContext.Bookmarks.Find(id);
            return View(location);
        }

        [HttpPost]
        public IActionResult DeleteBookmark(Bookmark bookmark)
        {
            BookmarkContext.Bookmarks.Remove(bookmark);
            BookmarkContext.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Unused right now.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public IActionResult DeleteLocation(int id)
        {
            var location = LocationContext.Locations.Find(id);
            return View(location);
        }
        
        /// <summary>
        /// Unused right now.
        /// </summary>
        /// <param name="location"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult DeleteLocation(Location location)
        {
            LocationContext.Locations.Remove(location);
            LocationContext.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

Dooter/Dooter/Controllers/HomeController.cs
using Dooter.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;

namespace Dooter.Controllers
{
    public class HomeController : Controller
    {
        //private readonly ILogger<HomeController> _logger;
        private LocationDBContext LocationContext { get; set; }
        private BookmarkDBContext BookmarkContext { get; set; }

        public HomeController(LocationDBContext locationContext, BookmarkDBContext bookmarkContext)
        {
            LocationContext = locationContext;
            BookmarkContext = bookmarkContext;
        }

        public IActionResult Index()
        {
            var locations = LocationContext.Locations.OrderBy(l => l.Name).ToList();
            return View(locations);
        }

        public IActionResult Bookmarks()
        {
            var bookmarks = BookmarkContext.Bookmarks.OrderBy(l => l.Name).ToList();
            return View(bookmarks);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        public IActionResult Profile()
        {
            return View();
        }

        public IActionResult Location_Information(int id)
        {
            var location = LocationContext.Locations.Find(id);
            return View(location);
        }

        public IActionResult Authenticate()
        {
            var accessClaims = new List<Claim>()
            {
                new Claim(ClaimTypes.Name, "John"),
                new Claim(ClaimTypes.Email, "John.Smith@gmail.com"),
                new Claim("Secret code", "TechPro 2020")
            };
            var googleClaims = new List<Claim>()
            {
                new Claim(ClaimTypes.Name, "John T Smith"),
                new Claim(ClaimTypes.Email, "John.Smith@gmail.com"),
                new Claim(ClaimTypes.MobilePhone, "778-778-9090")
            };

            var accessIdentity = new ClaimsIdentity(accessClaims, "Access Identity");
            var googleIdentity = new ClaimsIdentity(googleClaims, "Google Identity");

            var userPrincipal = new ClaimsPrincipal(new[] { accessIdentity, googleIdentity });

            HttpContext.SignInAsync(userPrincipal);

            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Dooter/Dooter/Views/Home/Bookmarks.cshtml
@{
    ViewData["Title"] = "Bookmarks";
}

<div class="container">
    <div class="d-flex justify-content-center mt-3">
        <div id="map" class="card border-0 map p-2"></div>
        <script>
            let map;
            function initMap() {
                map = new google.maps.Map(document.getElementById("map"), {
                    center: { lat: @Model[0].Latitude, lng: @Model[0].Longitude },
                    zoom: 12
                });
                const marker = new google.maps.Marker({
                    position: { lat:@Model[0].Latitude, lng: @Model[0].Longitude },
            map: map,
        });
    }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAW4970f3wiEpL6q7LcyW-z7pgH7fq6c94&callback=initMap&v=weekly"
                defer>
        </script>
        <div>
            <div class="card border-0 border-radius-sm p-2 search">
                <form action="#">
                    <input type="text"
                           placeholder=" Search Bookmarks..."
                           name="search">
                    <button>
                        <h4>Search</h4>
                    </button>
                </form>
            </div>
            <ul>
                @foreach (var bookmark in Model)
                {
                    <li class="card card-custom border-0 border-radius-sm card-bookmark p-2">
                        <div>
                            <h3 class="card-location-content">@bookmark.Name</h3>
                            <button class="location-rating">Delete</button>
                        </div>
                        <h3>@bookmark.Rating</h3>
                    </li>
                }
            </ul>
            @*<ul>
                <li class="card card-custom border-0 border-radius-sm card-bookmark p-2">
                    <div>
                        <h3 class="card-location-content">Gothic Tree Between Cemetary </h3>
                        <button class="location-rating">Delete</button>
                    </div>
                    <h3>3.5</h3>
                </li>
                <li class="card card-custom border-0 border-radius-sm card-bookmark p-2">
                    <div>
                        <h3 class="card-location-content">Gothic Tree Between Cemetary </h3>
                        <button class="location-rating">Delete</button>
                    </div>
                    <h3>3.5</h3>
                </li>
                <li class="card card-custom border-0 border-radius-sm card-bookmark p-2">
                    <div>
                        <h3 class="card-location-content">Gothic Tree Between Cemetary </h3>
                        <button class="location-rating">Delete</button>
                    </div>
                    <h3>3.5</h3>
                </li>
                <li class="card card-custom border-0 border-radius-sm card-bookmark p-2">
                    <div>
                        <h3 class="card-location-content">Gothic Tree Between Cemetary </h3>
                        <button class="location-rating">Delete</button>
                    </div>
                    <h3>3.5</h3>
                </li>
            </ul>*@
        </div>
    </div>
</div>

Dooter/Dooter/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div class="d-flex justify-content-center mt-3">
        
		<div id="map" class="card border-0 map p-2" ></div>
        <script>
            let map;
            function initMap() {
                map = new google.maps.Map(document.getElementById("map"), {
                    center: { lat: @Model[0].Latitude, lng: @Model[0].Longitude },
                    zoom: 12
                });
                const marker = new google.maps.Marker({
                    position: { lat:@Model[0].Latitude, lng: @Model[0].Longitude },
            map: map,
        });
    }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAW4970f3wiEpL6q7LcyW-z7pgH7fq6c94&callback=initMap&v=weekly"
                defer>
        </script>
        <div>
            <div class="card border-0 border-radius-sm p-2 search">
                <form action="#">
                    <input type="text"
                           placeholder=" Search Dooter..."
                           name="search">
                    <button>
                        <h4>Search</h4>
                    </button>
                </form>
            </div>
            <button class="add-spot">
                <a asp-controller="Functionality" asp-action="AddLocation" style="color: inherit; text-decoration: none">
                    <h4>Add Spot</h4>
                </a>
            </button>
            <ul>
                @foreach (var location in Model)
                {
                    <a asp-area="" style="color: inherit" asp-controller="Home" asp-action="Location_Information" asp-route-id="@location.LocationID">
                        <li class="card card-custom border-0 border-radius-sm card-location p-2">
                            <div>
                                <h3 class="card-location-content">@location.Name</h3>
                                <h3 class="location-rating">@location.Rating</h3>
                            </div>
                        </li>
                    </a>
                }
            </ul>

            @*<ul>
                <li class="card card-custom border-0 border-radius-sm card-location p-2">
                    <div>
                        <h3 class="card-location-content">Gothic Tree Between Cemetary </h3>
                        <h3 class="location-rating">3.5</h3>
                    </div>
                </li>
                <li class="card card-custom border-0 border-radius-sm card-location p-2">
                    <div>
                        <h3 class="card-location-content">Gothic Tree Between Cemetary </h3>
                        <h3 class="location-rating">3.5</h3>
                    </div>
                </li>
                <li class="card card-custom border-0 border-radius-sm card-location p-2">
                    <div>
                        <h3 class="card-location-content">Gothic Tree Between Cemetary </h3>
                        <h3 class="location-rating">3.5</h3>
                    </div>
                </li>
                <li class="card card-custom border-0 border-radius-sm card-location p-2">
                    <div>
                        <h3 class="card-location-content">Gothic Tree Between Cemetary </h3>
                        <h3 class="location-rating">3.5</h3>
                    </div>
                </li>
            </ul>*@
        </div>
    </div>
</div>

Dooter/Dooter/Views/Home/Location_Information.cshtml
@{
    ViewData["Title"] = "Location_Information";
}
@model Location
<head><script src="https://kit.fontawesome.com/cf1f826e4b.js" crossorigin="anonymous"></script></head>

<div class="row row-cols-2 g-3">

    <!-- Profile picture and description card -->

    <div class="col">
        <br>
        <div class="card">

            <img src="https://cdn.pixabay.com/photo/2022/09/20/20/16/oak-7468708_1280.jpg" class="card-img-top"
                 alt="user profile picture" height="300" />

            <div class="card-body">
                
                <h4 class="card-title">@Model.Name<span style="float:right"><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star">3.0</i></span></h4>
                
                <br>
                <p class="card-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </p>
                <h5 style="float: right">+ Add a review</h5>

            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">
                    <i class="fa-solid fa-user"></i>  User  <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"> 5.0</i>
                </h5>
                <p class="card-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </p>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">
                    <i class="fa-solid fa-user"></i>  User <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"> 4.0</i>
                </h5>
                <p class="card-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </p>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <h5 class="card-title">
                    <i class="fa-solid fa-user"></i>  User  <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"> 3.0</i>
                </h5>
                <p class="card-text">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </p>
            </div>
        </div>
    </div>


    <!--Map -->
    
    <div class="col">
        <div id="map" style="height:830px; width:auto;margin-top: 25px;"></div>
        <script>
            let map;
            function initMap(){
                map = new google.maps.Map(document.getElementById("map"),{
                    center: { lat: @Model.Latitude, lng: @Model.Latitude },
                    zoom: 12
                });
                const marker = new google.maps.Marker({
                    position: { lat: @Model.Latitude, lng: @Model.Latitude },
                    map: map,
                });

            }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAW4970f3wiEpL6q7LcyW-z7pgH7fq6c94&callback=initMap&v=weekly"
				defer> 
		</script>
        <br><br><br>
    </div>

    





</div>

Dooter/Dooter/Views/Home/Profile.cshtml
@{
    ViewData["Title"] = "Profile";
}
<head><script src="https://kit.fontawesome.com/cf1f826e4b.js" crossorigin="anonymous"></script></head>

<div class="row row-cols-3 g-4">

<!-- Profile picture and description card -->
    
  <div class="col">
      <br>
      <div class="card">

              <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png" class="card-img-top"
             alt="user profile picture" />

          <div class="card-body">
              <div class="text-center">
                  <h4 class="card-title">You The User</h4>
                  <p>lonelyguy@alone.com</p>
              </div>
              <br>
              <p class="card-text">
                  Hello am sad this is my description.
              </p>
              <br><br><br>
          </div>
      </div>
  </div>


    <!--Reviewed locations cards -->
  <div class="col">
      <br>
      <h5>Your Reviews</h5>
      <div class="card">
          <div class="card-body">
              <h5 class="card-title">
                  <i class="fa-solid fa-user"></i>  You  <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"> 5.0</i>
                  <i class="fa-solid fa-trash-can" style="float:right"></i>
              </h5>
              <p class="card-text">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </p>
          </div>
      </div>

      <div class="card">
          <div class="card-body">
              <h5 class="card-title">
                  <i class="fa-solid fa-user"></i>  You  <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"> 5.0</i>
                  <i class="fa-solid fa-trash-can" style="float:right"></i>
              </h5>
              <p class="card-text">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </p>
          </div>
      </div>

      <div class="card">
          <div class="card-body">
              <h5 class="card-title">
                  <i class="fa-solid fa-user"></i>  You  <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"> 5.0</i>
                  <i class="fa-solid fa-trash-can" style="float:right"></i>
              </h5>
              <p class="card-text">
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
              </p>
          </div>
      </div>

  </div>

  <!--Added locations cards -->
  <div class="col">
      <br>
      <h5>Spots you've added</h5>

      <div class="card">
          <div class="card-body">
              <h5 class="card-title">
                  Gothic Tree Between Cemetery
                  <i class="fa-solid fa-trash-can" style="float:right"></i>
              </h5>

              <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"> 5.0</i>
          </div>
      </div>

      <div class="card">
          <div class="card-body">
              <h5 class="card-title">
                  Gothic Tree Between Cemetery
                  <i class="fa-solid fa-trash-can" style="float:right"></i>
              </h5>

              <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"> 5.0</i>
          </div>
      </div>

      <div class="card">
          <div class="card-body">
              <h5 class="card-title">
                  Gothic Tree Between Cemetery
                  <i class="fa-solid fa-trash-can" style="float:right"></i>
              </h5>

              <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"> 5.0</i>
          </div>
      </div>

      <div class="card">
          <div class="card-body">
              <h5 class="card-title">
                  Gothic Tree Between Cemetery
                  <i class="fa-solid fa-trash-can" style="float:right"></i>
              </h5>

              <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"> 5.0</i>
          </div>
      </div>

      <div class="card">
          <div class="card-body">
              <h5 class="card-title">
                  Gothic Tree Between Cemetery
                  <i class="fa-solid fa-trash-can" style="float:right"></i>
              </h5>

              <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i><i class="fa-solid fa-star"> 5.0</i>
          </div>
      </div>

  </div>




</div>